\c socialnetwork;

INSERT INTO users(login, email, password, firstname, lastname) VALUES('pandalred', 'pandalred@me.com', '$2a$10$KOjovT62mnqly08Gup5ToOlVdHQ2q8i8lcDihaDGscPfkoNDRk26e', 'Arnaud', 'Thomazo');
INSERT INTO users(firstname, lastname, login, email, password) VALUES('Louis', 'Vezia', 'akabay', 'akabay@me.com', '$2a$10$KOjovT62mnqly08Gup5ToOlVdHQ2q8i8lcDihaDGscPfkoNDRk26e');
INSERT INTO users(firstname, lastname, login, email, password) VALUES('Axel', 'Vencatareddy', 'avencat', 'avencat@me.com', '$2a$10$KOjovT62mnqly08Gup5ToOlVdHQ2q8i8lcDihaDGscPfkoNDRk26e');
INSERT INTO users(firstname, lastname, login, email, password) VALUES('Céline', 'Couderc', 'julia', 'julia@me.com', '$2a$10$KOjovT62mnqly08Gup5ToOlVdHQ2q8i8lcDihaDGscPfkoNDRk26e');
INSERT INTO users(login, email, password) VALUES('beijingirl', 'beijingirl@me.com', '$2a$10$KOjovT62mnqly08Gup5ToOlVdHQ2q8i8lcDihaDGscPfkoNDRk26e');
INSERT INTO users(login, email, password) VALUES('venagen', 'venagen@me.com', '$2a$10$KOjovT62mnqly08Gup5ToOlVdHQ2q8i8lcDihaDGscPfkoNDRk26e');
INSERT INTO users(firstname, lastname, login, email, password) VALUES('Matthieu', 'Debrit', 'miniyoda', 'miniyoda@me.com', '$2a$10$KOjovT62mnqly08Gup5ToOlVdHQ2q8i8lcDihaDGscPfkoNDRk26e');

INSERT INTO posts(author_id, created, content) VALUES (1, make_timestamp(2017, 11, 23, 11, 52, 10), 'Quibus partiendo putat semel efficiatur docet veri putat ac concludaturque philosophiae efficiatur definitiones aliquid in iudicia omne tollit dividendo dividendo aliquid falsi nudus et semel sensibus non quidem dicitur tradit tollit iudicia modo rerum qua quo disserendi iudicia ratio falsi quaerendi logikh dividendo vester modo omne ut est quaerendi pro probatum mihi quo aliquid nudus mihi tradit non pro ambigua ambigua inermis non et ratio si ac iudicia partiendo sit semel non docet quae veri pro parte sit ostendit ratio docet probatum probatum nihil ponit qua tollit nudus ac omne ut parte quae et in inermis quidem inermis mihi probatum.');
INSERT INTO posts(author_id, created, content) VALUES (2, make_timestamp(2017, 11, 22, 10, 43, 10), 'Iamque scalas velut impetu per exsaturati divulsa per membrorum eosque funibus constrinxerunt exsaturati eodem flumen in per deformitatem ultimam conpage ultimam conpage scalas discursu mox mortuorum ultimam abiecerunt impetu funibus impetu in ampla constrinxerunt ad itidem constrinxerunt mox spatia funibus artuum ad in mox civitatis eosque per artuum civitatis raptavere praecipitem iamque superscandentes mortuorum et praecipitem ad et abiecerunt divulsa scalas superscandentes per ampla conpage eodem mox deformitatem per flumen funibus membrorum per acri spatia eosque corpora spatia velut Domitianum per truncata exsaturati eosque velut praecipitem velut per flumen eodem ad superscandentes ampla scalas membrorum iamque et conpage acri funibus.');
INSERT INTO posts(author_id, created, content) VALUES (3, make_timestamp(2017, 11, 21, 11, 52, 10), 'Seditionum hocque aurum consulta occultius militum genere navata verum ne exitiosa hoc diligens die die in occultius genere ut praepositus est tumor acueret praepotens eum verum et navata dilato consulta insidiarum missus ut verum Cabillona praepositus exitiosa in est fiduciam seditionum est Eusebius fiduciam deinde coeptantem ut praepotens locata coeptantem.');
INSERT INTO posts(author_id, created, content) VALUES (4, make_timestamp(2017, 11, 20, 11, 52, 10), 'Iam hunc copia consule restituit consule regeret ulla provenisset esse iam ex copia praeclarae Romano cum etiam pro Romano integre dedit inopia viri praeclarae hunc Carthaginiensibus dedit restituit restituit integre dedit dedit actitatum viri viri inopia cuius integre actitatum lassatis mora frumentum horreis consule est hunc victus pauloque est etiam.');
INSERT INTO posts(author_id, created, content) VALUES (5, make_timestamp(2017, 11, 21, 11, 52, 10), 'Mediam porrigitur interscindit navigabile porrigitur distentis verticibus sorte mediam dives late porrigitur sublimius terra qui lateri attolluntur minutis Isauria terra minutis spatiis spatiis terra viget bonis uberi pari Cilicia sorte sorte pari qui montis Calycadnus pari Calycadnus attolluntur terra interscindit adnexa porrigitur pari spatiis Isauria ad uberi et qui omnibus.');
INSERT INTO posts(author_id, created, content) VALUES (6, make_timestamp(2017, 10, 29, 11, 52, 10), 'Nobilitas liberis filia nobilitas diuturnum stipe florem amicorum amicorum causa alitur nobilitas Valerius conlaticia Scipionis erubesceret Valerius humatur Publicola liberis Publicola causa nobilitas humatur diuturnum humatur Reguli subsidiis liberis Publicola alitur causa florem pauperis pauperis liberis alitur absentia inops amicorum Publicola virginis ex diuturnum adultae humatur aerario nobilitas Valerius cum.');
INSERT INTO posts(author_id, created, content) VALUES (7, make_timestamp(2017, 11, 2, 11, 52, 10), 'Olim amor undique et cum esse omnia subvenire unum me patriam excipere pristinus reconciliat pro esse et existimatis rem meus omnia et olim in subvenire ac rursum Patres facitis animus impendentibus existimatis dimicatione tela intenta de existimatis atque ipsi) subvenire subire qui credite pristinus olim reconciliat mihi existimatis coegit cum.');
INSERT INTO posts(author_id, created, content) VALUES (1, make_timestamp(2017, 11, 24, 11, 52, 10), 'Populo quam vel dicere genere talis celeritas multis homines diebus illum tam sensum licet multis homines dicere deos autem sensum mortis difficile cum patribus ad excessit vita vel domum populo populo Scipioni hoc reductus licet quo in celeritas quid vesperum quos diebus talis vere celeberrimos ex fuit fuit licet Scipioni.');
INSERT INTO posts(author_id, created, content) VALUES (1, make_timestamp(2017, 11, 25, 11, 52, 10), 'Nihil contigerit contigerit lecturos tabernas nihil veritate ea alias ea nusquam a lecturos Romae propria nihil seditiones haec deflexerit seditiones tabernas seditiones si cum seditiones mirari nusquam harum nihil ad lecturos posse vilitates gererentur a contigerit lecturos oratio contigerit si tabernas similis harum monstranda harum vilitates digressurus haec et cum.');
INSERT INTO posts(author_id, created, content) VALUES (2, make_timestamp(2016, 9, 8, 11, 52, 10), 'Lenunculos apud ausos trucidarunt transitu semet quoque ausos veloci sole vel a sole fiducia cavatis et nandi legiones sole orto magnitudine dum innare fiducia et effusae et fiducia dum et fiducia impetu hiemabant conpage quae ausos temere cratibus ripam facillime a vel et permeare et amnem permeare effusae signis semet.');
INSERT INTO posts(author_id, created, content) VALUES (2, make_timestamp(2017, 11, 25, 11, 57, 10), 'Alios aut vellem deterritum qui quod iis artibus igitur aut necesse artibus minime quod te deterritum ita a tibi ne studiis ipse quamquam est De iis tenent doctrinis aut necesse satis iis iis non enim deterritum artibus artibus qui De De non enim inquam quod a te enim studiis aut.');
INSERT INTO posts(author_id, created, content) VALUES (3, make_timestamp(2017, 11, 26, 11, 52, 10), 'Tempus diligentiam quem amicitiis potius Quin quidem diligentiam praeceptum in id inciperemus quam odisse amare praecipiendum tempus valet est illud.');
INSERT INTO posts(author_id, created, content) VALUES (3, make_timestamp(2017, 11, 26, 9, 0, 10), 'Esse flatus qua praeter et vero potest flatus quorundam qua aestimant flatus caelibes caelibes aestimant Romae urbis liberis caelibes liberis.');
INSERT INTO posts(author_id, created, content) VALUES (4, make_timestamp(2017, 11, 26, 1, 5, 10), 'Eusebius frustra metu nec gradu suspensus confessione nulla temptata stetit.');
INSERT INTO posts(author_id, created, content) VALUES (5, make_timestamp(2017, 11, 26, 2, 52, 10), 'Muros die passurum carpento confirmans sed iurandi ablatis et statim.');
INSERT INTO posts(author_id, created, content) VALUES (5, make_timestamp(2017, 1, 23, 11, 52, 10), 'Principem narrabimus acerbum nimia in plagas quivis ut ut aemulis.');
INSERT INTO posts(author_id, created, content) VALUES (5, make_timestamp(2017, 9, 22, 11, 52, 10), 'Mox eosque scalas mortuorum impetu truncata ultimam artuum itidem coniunctos.');
INSERT INTO posts(author_id, created, content) VALUES (6, make_timestamp(2017, 11, 7, 11, 52, 10), 'Leviter contumaciter praegressa cessaveris in Caesar si proficiscere arcessitus postea conspectum iubebo nec quod abscessit arcessitus inconsiderate consistorium nec praeceptum arcessitus in dicto subiratus solo postea solo in quod cessaveris postea arcessitus postea consistorium solo tuas conspectum quod praegressa conspectum venit palatii cessaveris praegressa et venit venit inconsiderate postea diem.');
INSERT INTO posts(author_id, created, content) VALUES (7, make_timestamp(2017, 11, 8, 11, 52, 10), 'Extimas crebro partes si huius omnes fulminis partes et laevorsum parumque si quia flexo omnes laevorsum stationibus stationibus aliquando quod impetrasset Mesopotamiae impetrasset stationibus inquietari cuncta autem huius fulminis agrariis.');
INSERT INTO posts(author_id, created, content) VALUES (7, make_timestamp(2017, 10, 23, 11, 52, 8), 'Quoque in obstinatum in eius aliis haec intepescit non obstinatum aliquando poenae adulatorum more aliquando quod exitiale intepescit aliis progressu cohorte adulatorum factitarunt propositum in fertur propositum de haec fertur cohorte quod hoc poenae ob principes principes effervescebat elogio principes et quoque iussisse in factitarunt in vitium quoque exitiale et fertur adulatorum elogio intepescit in in poenae et revocari eius in hoc aliquando et vitium haec accendente quoque non ob oblato progressu quod hoc fertur revocari propositum obstinatum accendente exitiale ob in elogio vel fertur quod de fertur cohorte neminem progressu oblato iussisse oblato non effervescebat iussisse eius de vel.');

INSERT INTO comments(post_id, author_id, content) VALUES(1, 2, 'Et eos arta periculose arta.');
INSERT INTO comments(post_id, author_id, content) VALUES(1, 3, 'Morte voluntaria enim enim hausto.');
INSERT INTO comments(post_id, author_id, content) VALUES(1, 1, 'Paulus adoritur ad ferro negotiis.');
INSERT INTO comments(post_id, author_id, content) VALUES(2, 1, 'In visitur speciem iuris verum.');
INSERT INTO comments(post_id, author_id, content) VALUES(3, 1, 'Et eos arta periculose arta.');
INSERT INTO comments(post_id, author_id, content) VALUES(3, 2, 'Audire quae exprimebat in conspiratione.');
INSERT INTO comments(post_id, author_id, content) VALUES(3, 3, 'Eius insontium salutis offensis salutis.');
INSERT INTO comments(post_id, author_id, content) VALUES(13, 2, 'Praeter vilitates tabernas ad contigerit.');
INSERT INTO comments(post_id, author_id, content) VALUES(13, 3, 'Nec tamquam pertinacius et torvum.');
INSERT INTO comments(post_id, author_id, content) VALUES(13, 4, 'Aliud illa propter si ut.');
INSERT INTO comments(post_id, author_id, content) VALUES(13, 1, 'Siquae universis per copia lactisque.');
INSERT INTO comments(post_id, author_id, content) VALUES(13, 2, 'Tamen nuptias ubi vigore instituta cum offertur artuum offertur sunt vel vel nobilium inpigre dextris pergunt dextris inpigre quidam vel cavatis cavatis inpigre inminuto ita sunt offertur haec aurum tamen inpigre inpigre aurum instituta haec observentur pergunt cum pergunt rogati offertur ubi haec dextris vigore Spoletium tamen quidam tutius vigore vigore artuum inpigre ubi nobilium ad cavatis ad observentur artuum vel ad usque quidam vigore inminuto cum usque inminuto nuptias pergunt aurum artuum aurum ubi quidam observentur ubi nobilium quidam manibus aurum haec tamen tutius aurum ad rogati ubi ad inpigre observentur manibus haec observentur cavatis cum vigore artuum tutius.');
INSERT INTO comments(post_id, author_id, content) VALUES(13, 3, 'Quibus iste de distinguantur sublatum vero in parte modo altera distinguantur definitiones plane quae inermis ut ratio tollit dicitur quae philosophiae pro aliquid partiendo est aliquid quidem non iste ratio definitiones iudicia est tradit ostendit ac ratio esse efficiatur in tradit si de in sit modo parte ut falsi falsi efficiatur aliquid ostendit sublatum non quaerendi et dividendo partiendo ambigua nihil quae non pro partiendo sensibus si altera iste altera aliquid ostendit concludaturque ponit iste est ostendit sublatum vester tollit quibus partiendo quidem quaerendi et est est et ratio dicitur aliquid in modo disserendi falsi modo solvantur solvantur quaerendi partiendo.');

INSERT INTO post_likes(post_id, user_id) VALUES(20, 3);
INSERT INTO post_likes(post_id, user_id) VALUES(20, 2);
INSERT INTO post_likes(post_id, user_id) VALUES(20, 1);
INSERT INTO post_likes(post_id, user_id) VALUES(14, 3);
INSERT INTO post_likes(post_id, user_id) VALUES(17, 3);
INSERT INTO post_likes(post_id, user_id) VALUES(16, 3);
INSERT INTO post_likes(post_id, user_id) VALUES(15, 3);
INSERT INTO post_likes(post_id, user_id) VALUES(13, 1);
INSERT INTO post_likes(post_id, user_id) VALUES(13, 2);
INSERT INTO post_likes(post_id, user_id) VALUES(13, 6);
INSERT INTO post_likes(post_id, user_id) VALUES(13, 7);
INSERT INTO post_likes(post_id, user_id) VALUES(13, 5);
INSERT INTO post_likes(post_id, user_id) VALUES(13, 4);
INSERT INTO post_likes(post_id, user_id) VALUES(16, 6);
INSERT INTO post_likes(post_id, user_id) VALUES(15, 7);
INSERT INTO post_likes(post_id, user_id) VALUES(11, 3);

INSERT INTO comment_likes(comment_id, user_id) VALUES(12, 3);
INSERT INTO comment_likes(comment_id, user_id) VALUES(13, 2);
INSERT INTO comment_likes(comment_id, user_id) VALUES(11, 3);
INSERT INTO comment_likes(comment_id, user_id) VALUES(4, 3);
INSERT INTO comment_likes(comment_id, user_id) VALUES(8, 3);

INSERT INTO friendships(follower_id, following_id) VALUES(3, 1);
INSERT INTO friendships(follower_id, following_id) VALUES(3, 2);
INSERT INTO friendships(follower_id, following_id) VALUES(5, 3);
INSERT INTO friendships(follower_id, following_id) VALUES(3, 4);
INSERT INTO friendships(follower_id, following_id) VALUES(3, 5);
INSERT INTO friendships(follower_id, following_id) VALUES(3, 6);
INSERT INTO friendships(follower_id, following_id) VALUES(3, 7);
INSERT INTO friendships(follower_id, following_id) VALUES(1, 2);
INSERT INTO friendships(follower_id, following_id) VALUES(1, 3);
INSERT INTO friendships(follower_id, following_id) VALUES(2, 1);
INSERT INTO friendships(follower_id, following_id) VALUES(2, 3);
INSERT INTO friendships(follower_id, following_id) VALUES(4, 3);
